// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathLeafNextID = "/leaf/next-id"

// LeafBMServer is the server API for Leaf service.
type LeafBMServer interface {
	NextID(ctx context.Context, req *LeafReq) (resp *LeafReply, err error)
}

var LeafSvc LeafBMServer

func leafNextID(c *bm.Context) {
	p := new(LeafReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := LeafSvc.NextID(c, p)
	c.JSON(resp, err)
}

// RegisterLeafBMServer Register the blademaster route
func RegisterLeafBMServer(e *bm.Engine, server LeafBMServer) {
	LeafSvc = server
	e.GET("/leaf/next-id", leafNextID)
}
