
redisExpire = "24h"
redisDb = 2

[redis]
	name = "account.token"
	proto = "tcp"
	addr = "212.64.50.167:2224"
	auth = "itswcg"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
