// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathAuthToken = "/auth.service.Auth/Token"

// AuthBMServer is the server API for Auth service.
type AuthBMServer interface {
	Token(ctx context.Context, req *TokenReq) (resp *TokenReply, err error)
}

var AuthSvc AuthBMServer

func authToken(c *bm.Context) {
	p := new(TokenReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := AuthSvc.Token(c, p)
	c.JSON(resp, err)
}

// RegisterAuthBMServer Register the blademaster route
func RegisterAuthBMServer(e *bm.Engine, server AuthBMServer) {
	AuthSvc = server
	e.GET("/auth.service.Auth/Token", authToken)
}
