// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathAccountToken = "/auth.service.Account/Token"

// AccountBMServer is the server API for Account service.
type AccountBMServer interface {
	Token(ctx context.Context, req *TokenReq) (resp *TokenReply, err error)
}

var AccountSvc AccountBMServer

func accountToken(c *bm.Context) {
	p := new(TokenReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := AccountSvc.Token(c, p)
	c.JSON(resp, err)
}

// RegisterAccountBMServer Register the blademaster route
func RegisterAccountBMServer(e *bm.Engine, server AccountBMServer) {
	AccountSvc = server
	e.GET("/auth.service.Account/Token", accountToken)
}
